sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  - "pypy"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls

# coveralls
service_name: travis-pro
repo_token: 3HHKgnpaX6qT41o42B3vTld39dHYVjzuZ

# command to run tests
script: nosetests

script:
  coverage run --source flask_validator setup.py test
after_success:
  coveralls

